### ISSUE TITLE
mold only reports duplicate symbols when using LTO

### ISSUE THREAD

**Issue by enno-t** [rui314/mold#1421]
When building redict today I was greeted with an error like this:
mold: error: duplicate symbol: ../deps/hiredict/libhiredict.a(test.o): redict-benchmark.o: main

After some poking around in redict and my build script I tried linking with GNU ld instead, wich built redict without issues.

Further poking showed that mold only reports duplicate symbols if LTO is used and does so with both gcc and clang.

After reverting 9306f69a615bd54814263c59a9ff7f78a205753a (the fix for #1414) mold builds with and without LTO.

[clang-log.txt](https://github.com/user-attachments/files/19037921/clang-log.txt)
[gcc-log.txt](https://github.com/user-attachments/files/19037922/gcc-log.txt)

mold --version
mold 2.36.0 (11a62121e31ca46a88f5d94e4d356c6c888a22c7; compatible with GNU ld)

and

mold 2.37.0 (3981f4f3d45b3b71b6dcbb550cbc0d8454969070; compatible with GNU ld)

gcc --version
gcc (Gentoo Hardened 14.2.1_p20241221 p7) 14.2.1 20241221

GNU ld version
GNU ld (Gentoo 2.43 p3) 2.43.1

clang --version
clang version 19.1.7

redict version
redict 7.3.2 (d12b0cf438664a14999b23a6a1c5b6f39a5f7e37) aka latest main

LDFLAGS
-Wl,-z,defs -Wl,-z,now -Wl,-z,relro -Wl,-z,nodlopen -Wl,-z,noexecstack -Wl,--as-needed -Wl,--no-copy-dt-needed-entries -Wl,--repro -Wl,-o/tmp/gcc -fuse-ld=mold

CFLAGS
-pipe -march=native -O2 -fstack-protector-strong -fcf-protection -fpie -fPIC -std=c99 -U_DEFAULT_SOURCE -D_DEFAULT_SOURCE -fno-delete-null-pointer-checks -fno-strict-overflow -fno-strict-aliasing -ftrivial-auto-var-init=zero -fstrict-flex-arrays=3 -fstack-clash-protection -Wformat=2 -Wimplicit-fallthrough -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fexceptions -flto=auto -Wtrampolines -fhardened -Wno-hardened -Werror=format-security

**Comment by enno-t** [comment]
Output of -Wl,--repro is avaiable at [enno-t/mold/issue-1421-repro](https://github.com/enno-t/mold-issue-1421-repro)

**Comment by FerdiScholten** [comment]
I can confirm this, every LTO build using mold 2.37 fails with mold: error: duplicate symbol: 
Reverting to mold 2.36 for now fixes the problem

**Comment by HanabishiRecca** [comment]
Not every LTO build errors out. But I did hit that at least when trying to build Mesa and Pipewire.

**Comment by enno-t** [comment]
> Not every LTO build errors out. But I did hit that at least when trying to build Mesa and Pipewire.

Yeah, so far I've only been able to hit this issue with redict (maybe because LTO is not part of my standard CFLAGS?)

**Comment by satmandu** [comment]
Can confirm the same when building with mold 2.37 and LTO trying to build LLVM 20.1.

```bash
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_sd_to_hf.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_df_to_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_addsub_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_tf.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_xf_to_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_div_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_tf_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_sf_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_usi.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_le_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_udi.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_mul_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_ge_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_gt_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_sd_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(sfp-exceptions.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.dx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_eq_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_si_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_unord_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(fixunstfsi.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_unord_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_hf_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_tf_to_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_mulhc3.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_divhc3.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_hf_to_sd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_di_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_td_to_hf.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_sd_to_dd.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(fixunstfdi.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
    mold: error: duplicate symbol: /usr/local/lib/gcc/i686-cros-linux-gnu/14/libgcc.a(_usi_to_td.o): /usr/local/lib/gcc/i686-cros-linux-gnu/14/crtbeginS.o: __x86.get_pc_thunk.bx
```

**Comment by satmandu** [comment]
Reverting to mold 2.36 resolves the issue.

**Comment by FerdiScholten** [comment]
> I can confirm this, every LTO build using mold 2.37 fails with mold: error: duplicate symbol: Reverting to mold 2.36 for now fixes the problem

More specific, building Avidemux; libplacebo; FFmpeg and MPV all failed, then I reverted to 2.36 and they all build flawlessly

**Comment by rui314** [comment]
I'll fix the issue and release it as 2.37.1. Please hold on.

**Comment by satmandu** [comment]
Sorry to necrobump, but i'm seeing this error again trying to compile the current version of git (2.52.0) on armv7l with mold 2.40.4 and GCC 15.2.
```
[771/1057] Linking target git-shell
FAILED: [code=1] git-shell 
cc  -o git-shell git-shell.p/shell.c.o -flto -Wl,--as-needed -Wl,--no-undefined -fuse-ld=mold -Wl,-O1 -pie -flto=auto '-Wl,-rpath,$ORIGIN/src' -Wl,--start-group libcommon-main.a libgit.a src/libgitcore.a /usr/local/lib/libz-ng.so -pthread /usr/local/lib/libpcre2-8.so /usr/local/lib/libexpat.so -lnsl -lresolv /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lnsl -lresolv -lnsl -lresolv -Wl,--end-group
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __udivsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __aeabi_uidiv
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __divsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __aeabi_idiv
collect2: error: ld returned 1 exit status
[772/1057] Linking target git-sh-i18n--envsubst
FAILED: [code=1] git-sh-i18n--envsubst 
cc  -o git-sh-i18n--envsubst git-sh-i18n--envsubst.p/sh-i18n--envsubst.c.o -flto -Wl,--as-needed -Wl,--no-undefined -fuse-ld=mold -Wl,-O1 -pie -flto=auto '-Wl,-rpath,$ORIGIN/src' -Wl,--start-group libcommon-main.a libgit.a src/libgitcore.a /usr/local/lib/libz-ng.so -pthread /usr/local/lib/libpcre2-8.so /usr/local/lib/libexpat.so -lnsl -lresolv /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lnsl -lresolv -lnsl -lresolv -Wl,--end-group
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __udivsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __divsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __aeabi_idiv
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __aeabi_uidiv
collect2: error: ld returned 1 exit status
[773/1057] Linking target git-daemon
FAILED: [code=1] git-daemon 
cc  -o git-daemon git-daemon.p/daemon.c.o -flto -Wl,--as-needed -Wl,--no-undefined -fuse-ld=mold -Wl,-O1 -pie -flto=auto '-Wl,-rpath,$ORIGIN/src' -Wl,--start-group libcommon-main.a libgit.a src/libgitcore.a /usr/local/lib/libz-ng.so -pthread /usr/local/lib/libpcre2-8.so /usr/local/lib/libexpat.so -lnsl -lresolv /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lnsl -lresolv -lnsl -lresolv -Wl,--end-group
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __udivsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __divsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __aeabi_idiv
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __aeabi_uidiv
collect2: error: ld returned 1 exit status
[774/1057] Linking target git
FAILED: [code=1] git 
cc  -o git git.p/builtin_add.c.o git.p/builtin_am.c.o git.p/builtin_annotate.c.o git.p/builtin_apply.c.o git.p/builtin_archive.c.o git.p/builtin_backfill.c.o git.p/builtin_bisect.c.o git.p/builtin_blame.c.o git.p/builtin_branch.c.o git.p/builtin_bugreport.c.o git.p/builtin_bundle.c.o git.p/builtin_cat-file.c.o git.p/builtin_check-attr.c.o git.p/builtin_check-ignore.c.o git.p/builtin_check-mailmap.c.o git.p/builtin_check-ref-format.c.o git.p/builtin_checkout--worker.c.o git.p/builtin_checkout-index.c.o git.p/builtin_checkout.c.o git.p/builtin_clean.c.o git.p/builtin_clone.c.o git.p/builtin_column.c.o git.p/builtin_commit-graph.c.o git.p/builtin_commit-tree.c.o git.p/builtin_commit.c.o git.p/builtin_config.c.o git.p/builtin_count-objects.c.o git.p/builtin_credential-cache--daemon.c.o git.p/builtin_credential-cache.c.o git.p/builtin_credential-store.c.o git.p/builtin_credential.c.o git.p/builtin_describe.c.o git.p/builtin_diagnose.c.o git.p/builtin_diff-files.c.o git.p/builtin_diff-index.c.o git.p/builtin_diff-pairs.c.o git.p/builtin_diff-tree.c.o git.p/builtin_diff.c.o git.p/builtin_difftool.c.o git.p/builtin_fast-export.c.o git.p/builtin_fast-import.c.o git.p/builtin_fetch-pack.c.o git.p/builtin_fetch.c.o git.p/builtin_fmt-merge-msg.c.o git.p/builtin_for-each-ref.c.o git.p/builtin_for-each-repo.c.o git.p/builtin_fsck.c.o git.p/builtin_fsmonitor--daemon.c.o git.p/builtin_gc.c.o git.p/builtin_get-tar-commit-id.c.o git.p/builtin_grep.c.o git.p/builtin_hash-object.c.o git.p/builtin_help.c.o git.p/builtin_hook.c.o git.p/builtin_index-pack.c.o git.p/builtin_init-db.c.o git.p/builtin_interpret-trailers.c.o git.p/builtin_last-modified.c.o git.p/builtin_log.c.o git.p/builtin_ls-files.c.o git.p/builtin_ls-remote.c.o git.p/builtin_ls-tree.c.o git.p/builtin_mailinfo.c.o git.p/builtin_mailsplit.c.o git.p/builtin_merge-base.c.o git.p/builtin_merge-file.c.o git.p/builtin_merge-index.c.o git.p/builtin_merge-ours.c.o git.p/builtin_merge-recursive.c.o git.p/builtin_merge-tree.c.o git.p/builtin_merge.c.o git.p/builtin_mktag.c.o git.p/builtin_mktree.c.o git.p/builtin_multi-pack-index.c.o git.p/builtin_mv.c.o git.p/builtin_name-rev.c.o git.p/builtin_notes.c.o git.p/builtin_pack-objects.c.o git.p/builtin_pack-refs.c.o git.p/builtin_patch-id.c.o git.p/builtin_prune-packed.c.o git.p/builtin_prune.c.o git.p/builtin_pull.c.o git.p/builtin_push.c.o git.p/builtin_range-diff.c.o git.p/builtin_read-tree.c.o git.p/builtin_rebase.c.o git.p/builtin_receive-pack.c.o git.p/builtin_reflog.c.o git.p/builtin_refs.c.o git.p/builtin_remote-ext.c.o git.p/builtin_remote-fd.c.o git.p/builtin_remote.c.o git.p/builtin_repack.c.o git.p/builtin_replace.c.o git.p/builtin_replay.c.o git.p/builtin_repo.c.o git.p/builtin_rerere.c.o git.p/builtin_reset.c.o git.p/builtin_rev-list.c.o git.p/builtin_rev-parse.c.o git.p/builtin_revert.c.o git.p/builtin_rm.c.o git.p/builtin_send-pack.c.o git.p/builtin_shortlog.c.o git.p/builtin_show-branch.c.o git.p/builtin_show-index.c.o git.p/builtin_show-ref.c.o git.p/builtin_sparse-checkout.c.o git.p/builtin_stash.c.o git.p/builtin_stripspace.c.o git.p/builtin_submodule--helper.c.o git.p/builtin_symbolic-ref.c.o git.p/builtin_tag.c.o git.p/builtin_unpack-file.c.o git.p/builtin_unpack-objects.c.o git.p/builtin_update-index.c.o git.p/builtin_update-ref.c.o git.p/builtin_update-server-info.c.o git.p/builtin_upload-archive.c.o git.p/builtin_upload-pack.c.o git.p/builtin_var.c.o git.p/builtin_verify-commit.c.o git.p/builtin_verify-pack.c.o git.p/builtin_verify-tag.c.o git.p/builtin_worktree.c.o git.p/builtin_write-tree.c.o git.p/builtin_pack-redundant.c.o git.p/git.c.o -flto -Wl,--as-needed -Wl,--no-undefined -fuse-ld=mold -Wl,-O1 -pie -flto=auto '-Wl,-rpath,$ORIGIN/src' -Wl,--start-group libcommon-main.a libgit.a src/libgitcore.a /usr/local/lib/libz-ng.so -pthread /usr/local/lib/libpcre2-8.so /usr/local/lib/libexpat.so -lnsl -lresolv /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lnsl -lresolv -lnsl -lresolv -Wl,--end-group
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __udivsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __aeabi_uidiv
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __divsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/15/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __aeabi_idiv
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
There was a build error.
`CFLAGS="-O3 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto=auto -flto=auto" CXXFLAGS="-O3 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto=auto -flto=auto" FCFLAGS="-O3 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto=auto -flto=auto" FFLAGS="-O3 -pipe -ffat-lto-objects -fPIC -fuse-ld=mold  -flto=auto -flto=auto" LDFLAGS="-flto=auto" CREW_PRELOAD_ENABLE_COMPILE_HACKS="1" CC_LD="mold" CXX_LD="mold" CREW_PRELOAD_NO_MOLD="0" /usr/local/bin/jobserver_pool.py -j 4 ninja -C ./builddir` exited with 1
```
I did not have issues on `i686` or `x86_64`.

Should I open a new issue?

**Comment by myrrc** [comment]
I can reproduce this as well with duckdb's 1.4.3 debug build

```
mold: error: duplicate symbol: extension/vortex/libvortex_duckdb.a(5811b530fb0dbdaf-file_system.o): src/libduckdb_static.a(ub_duckdb_common.cpp.o): duckdb::FileFlags::FILE_FLAGS_READ
mold: error: duplicate symbol: extension/vortex/libvortex_duckdb.a(5811b530fb0dbdaf-file_system.o): src/libduckdb_static.a(ub_duckdb_common.cpp.o): duckdb::FileFlags::FILE_FLAGS_PARALLEL_ACCESS
```

This doesn't reproduce in release builds, and also doesn't reproduce with ld, lld, and gold

**Comment by rui314** [comment]
Please try again with the above change.

**Comment by myrrc** [comment]
Thanks, it doesn't reproduce anymore.

**Comment by satmandu** [comment]
I am still seeing this issue on armv7l with a build of git `2.55.0` with mold `2.41.0`:
```
[795/1085] Linking target git-shell
FAILED: [code=1] git-shell
cc  -o git-shell git-shell.p/shell.c.o -flto=auto -Wl,--as-needed -Wl,--no-undefined -fuse-ld=mold -Wl,-O1 -pie -flto=auto '-Wl,-rpath,$ORIGIN/src' -Wl,--start-group libcommon-main.a libcompat.a src/libgitcore.a libgit.a /usr/local/lib/libz-ng.so -pthread /usr/local/lib/libpcre2-8.so /usr/local/lib/libexpat.so -lnsl -lresolv /usr/local/lib/libssl.so /usr/local/lib/libcrypto.so -lnsl -lresolv -lnsl -lresolv -lnsl -lresolv -Wl,--end-group
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/16/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __udivsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/16/libgcc.a(_udivsi3.o): src/libgitcore.a(63f8a0b8a638da8c-udivsi3.o): __aeabi_uidiv
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/16/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __divsi3
mold: error: duplicate symbol: /usr/local/lib/gcc/armv7l-cros-linux-gnueabihf/16/libgcc.a(_divsi3.o): src/libgitcore.a(63f8a0b8a638da8c-divsi3.o): __aeabi_idiv
collect2: error: ld returned 1 exit status
...
```
Do I need to rebuild libgcc?

**Comment by rui314** [comment]
632a0eea should fix the issue.
