### ISSUE TITLE
Duplicate symbol errors after updating from 2.36 to 2.37

### ISSUE THREAD

**Issue by Zyrin** [rui314/mold#1428]
After updating from 2.36 to 2.37 we are getting duplicate symbol errors like the following:
```
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_paritydi2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __parityti2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(truncxfhf2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __truncxfhf2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(negtf2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __negtf2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(subtf3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __subtf3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(unordtf2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __unordtf2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixtfsi.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixtfsi
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixunstfsi.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixunstfsi
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floatsitf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floatsitf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floatunsitf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floatunsitf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixtfdi.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixtfdi
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixunstfdi.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixunstfdi
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floatditf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floatditf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floatunditf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floatunditf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixtfti.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixtfti
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(fixunstfti.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __fixunstfti
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floattitf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floattitf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(floatuntitf.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __floatuntitf
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(extendhfsf2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __extendhfsf2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(extendhfdf2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __extendhfdf2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_divhc3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __divhc3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_mulhc3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __mulhc3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_subvdi3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __subvti3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_mulvsi3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __mulvdi3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_mulvsi3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __mulvsi3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_mulvdi3.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __mulvti3
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_negvsi2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __negvdi2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_negvsi2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __negvsi2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_negvdi2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __negvti2
mold: error: duplicate symbol: /usr/lib/gcc/x86_64-linux-gnu/12/libgcc.a(_ffssi2.o): /usr/lib/x86_64-linux-gnu/libgcc_s.so.1: __ffsdi2
...
```
We are using Ubuntu 22.04 with gcc 12.3.0.

**Comment by rui314** [comment]
Please try again with 2.37.1.

**Comment by Zyrin** [comment]
2.37.1 works. Thanks :)
