### ISSUE TITLE
has_single_bit requires #include <bit>

### ISSUE THREAD

**Issue by dilyn-corner** [rui314/mold#308]
https://github.com/rui314/mold/blob/0d542fb3bc9553fc3e48558a8c22b6b08d3d1d85/mold.h#L163

Introduced by 6c9bb0d7ff5e863775e50f5a80fe64cefff34a23

Building on musl with LLVM/Clang/lld/libc++.

Adding `#include <bit>` to `mold.h` resolves the below build time error:

```
mkdir -p out/elf
touch out/elf/.keep
mkdir -p out/macho
touch out/macho/.keep
c++ -std=c++20 -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -DMOLD_VERSION=\"1.0.2\" -DLIBDIR="\"/usr/local/lib\"" -Ithird-party/mimalloc/include -Ithird-party/tbb/include -Ithird-party/xxhash  -MT out/compress.o -MMD -MP -MF out/compress.d -O2 -c -o out/compress.o compress.cc
In file included from compress.cc:15:
./mold.h:163:15: error: no member named 'has_single_bit' in namespace 'std'
  assert(std::has_single_bit(align));
         ~~~~~^
/usr/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from compress.cc:15:
./mold.h:168:15: error: no member named 'has_single_bit' in namespace 'std'
  assert(std::has_single_bit(align));
         ~~~~~^
/usr/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from compress.cc:15:
./mold.h:299:49: error: no member named 'bit_ceil' in namespace 'std'
    nbuckets = std::max<i64>(MIN_NBUCKETS, std::bit_ceil<u64>(nbuckets));
                                           ~~~~~^
./mold.h:299:58: error: unexpected type name 'u64': expected expression
    nbuckets = std::max<i64>(MIN_NBUCKETS, std::bit_ceil<u64>(nbuckets));
                                                         ^
./mold.h:311:17: error: no member named 'has_single_bit' in namespace 'std'
    assert(std::has_single_bit<u64>(nbuckets));
           ~~~~~^
/usr/include/assert.h:8:28: note: expanded from macro 'assert'
#define assert(x) ((void)((x) || (__assert_fail(#x, __FILE__, __LINE__, __func__),0)))
                           ^
In file included from compress.cc:15:
./mold.h:311:32: error: unexpected type name 'u64': expected expression
    assert(std::has_single_bit<u64>(nbuckets));
                               ^
./mold.h:429:57: error: no member named 'countl_zero' in namespace 'std'
    update_maximum(buckets[hash & (NBUCKETS - 1)], std::countl_zero(hash) + 1);
                                                   ~~~~~^
7 errors generated.
gmake: *** [Makefile:140: out/compress.o] Error 1
```

**Comment by truboxl** [comment]
Anyone know which version of Clang support this? Adding `<bit>` doesn't seem to fix it for me. I think I am using Clang 12 (Android NDK)...

**Comment by dilyn-corner** [comment]
This was with Clang 13

**Comment by rui314** [comment]
@truboxl Does reverting https://github.com/rui314/mold/commit/6c9bb0d7ff5e863775e50f5a80fe64cefff34a23 (you can do that by `git revert 6c9bb0d7ff5e863775e50f5a80fe64cefff34a23`) fix your problem? If so, I'm happy to do that.

**Comment by truboxl** [comment]
Sorry for the late reply

@rui314 
Yes that works

For reference, the latest NDK r23 includes this bit header file which seems to be missing has_single_bit...
https://android.googlesource.com/toolchain/prebuilts/ndk/r23/+/refs/heads/master/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/c++/v1/bit

I haven't check out NDK r24 beta which should be using Clang 14...

There's no activity here so I assume r24 is pretty much the same? I think C++20 on Android is barely getting started...
https://android.googlesource.com/platform/prebuilts/ndk/+/refs/heads/master/current/sources/cxx-stl/llvm-libc++/include/bit

**Comment by rui314** [comment]
I submitted a change to remove the uses of `std::has_single_bit` from our codebase. Please verify if you have time.

**Comment by truboxl** [comment]
Oops forgot to mention std::bit_ceil 😅
```
elf/output-chunks.cc:1285:22: error: no member named 'bit_ceil' in namespace 'std'
    num_bloom = std::bit_ceil<u64>(num_bits / ELFCLASS_BITS);
                ~~~~~^
elf/output-chunks.cc:1285:31: error: unexpected type name 'u64': expected expression
    num_bloom = std::bit_ceil<u64>(num_bits / ELFCLASS_BITS);
                              ^
2 errors generated.

macho/../mold.h:300:49: error: no member named 'bit_ceil' in namespace 'std'
    nbuckets = std::max<i64>(MIN_NBUCKETS, std::bit_ceil<u64>(nbuckets));
                                           ~~~~~^
macho/../mold.h:300:58: error: unexpected type name 'u64': expected expression
    nbuckets = std::max<i64>(MIN_NBUCKETS, std::bit_ceil<u64>(nbuckets));
                                                         ^
2 errors generated.
```

**Comment by rui314** [comment]
I removed the uses of `std::bit_ceil` from our codebase.

**Comment by truboxl** [comment]
I have gone ahead and log the issue as android/ndk#1664 to see what NDK folks think about this. Maybe they will list out timeline to add support for this.

**Comment by rui314** [comment]
Thanks. I don't know if Android NDK officially supports C++20, but if it does, then it's clearly a bug.
