### ISSUE TITLE
mold-2.40.4 fails to link >=btrfs-progs-6.14

### ISSUE THREAD

**Issue by zyxhere** [rui314/mold#1509]
Steps to reproduce:
```
wget https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v6.16.tar.xz
tar xf btrfs-progs*
export CFLAGS="-O2 -flto=auto -fuse-ld=mold"
export LDFLAGS=$CFLAGS
cd btrfs-progs*
./configure --disable-lzo --disable-documentation --disable-libudev --disable-zstd
```

See errors:
```
gcc -o btrfs-corrupt-block kernel-lib/list_sort.o kernel-lib/raid56.o kernel-lib/rbtree.o kernel-lib/tables.o kernel-shared/accessors.o kernel-shared/async-thread.o kernel-shared/backref.o kernel-shared/ctree.o kernel-shared/delayed-ref.o kernel-shared/dir-item.o kernel-shared/disk-io.o kernel-shared/extent-io-tree.o kernel-shared/extent-tree.o kernel-shared/extent_io.o kernel-shared/file-item.o kernel-shared/file.o kernel-shared/free-space-cache.o kernel-shared/free-space-tree.o kernel-shared/inode-item.o kernel-shared/inode.o kernel-shared/locking.o kernel-shared/messages.o kernel-shared/print-tree.o kernel-shared/root-tree.o kernel-shared/transaction.o kernel-shared/tree-checker.o kernel-shared/ulist.o kernel-shared/uuid-tree.o kernel-shared/volumes.o kernel-shared/zoned.o common/array.o common/compat.o common/cpu-utils.o common/device-scan.o common/device-utils.o common/extent-cache.o common/extent-tree-utils.o common/root-tree-utils.o common/filesystem-utils.o common/format-output.o common/fsfeatures.o common/help.o common/inject-error.o common/messages.o common/open-utils.o common/parse-utils.o common/path-utils.o common/rbtree-utils.o common/send-stream.o common/send-utils.o common/sort-utils.o common/string-table.o common/string-utils.o common/sysfs-utils.o common/task-utils.o common/units.o common/utils.o check/qgroup-verify.o check/repair.o cmds/receive-dump.o crypto/crc32c.o crypto/hash.o crypto/xxhash.o crypto/sha224-256.o crypto/blake2b-ref.o crypto/blake2b-sse2.o crypto/blake2b-sse41.o crypto/blake2b-avx2.o crypto/sha256-x86.o crypto/crc32c-pcl-intel-asm_64.o libbtrfsutil/stubs.o libbtrfsutil/subvolume.o btrfs-corrupt-block.o \
	 \
	libbtrfsutil.a \
	-flto=auto -fuse-ld=mold -O2 -rdynamic -L.   -luuid -lblkid  -L. -pthread  
  LN       libbtrfsutil.so
ln -s -f libbtrfsutil.so.1.3.2 libbtrfsutil.so
  LN       libbtrfsutil.so.1
ln -s -f libbtrfsutil.so.1.3.2 libbtrfsutil.so.1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:710: btrfs-map-logical] Error 1
make: *** Waiting for unfinished jobs....
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:710: btrfs-corrupt-block] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:710: btrfs-find-root] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:769: btrfs-image] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:710: btrfs-select-super] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:753: mkfs.btrfs] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:761: btrfstune] Error 1
mold: error: /usr/lib64/libblkid.so: --no-allow-shlib-undefined: undefined symbol: reallocarray
collect2: error: ld returned 1 exit status
make: *** [Makefile:717: btrfs] Error 1
```

The bfd linker can link fine but not mold. Also passing --enable-libudev to configure gets rid of the errors. gcc version is 14.3

**Comment by zyxhere** [comment]
Downstream bug: https://bugs.gentoo.org/961969

**Comment by rui314** [comment]
Thank you for your report! This issue looks real and actually not limited to LTO. I'll try to address it later this week.

**Comment by etwoo** [comment]
I was able to get this working with `btrfs-progs-v6.16.tar.xz` and mold 2.40.4 by adjusting LDFLAGS, per the docs on the [-Wl,option](https://gcc.gnu.org/onlinedocs/gcc-15.1.0/gcc/Link-Options.html#:~:text=%2DWl,output%2Emap%2E) form.

```diff
$ diff -u repro.sh.orig repro.sh
--- repro.sh.orig       2025-09-20 08:48:26.866459282 +0000
+++ repro.sh    2025-09-20 08:48:04.844777642 +0000
@@ -9,7 +9,7 @@
 
 export PATH="$PWD:$PATH"
 export CFLAGS="-O2 -flto=auto -fuse-ld=mold"
-export LDFLAGS=$CFLAGS
+export LDFLAGS="-Wl,-flto"
 cd btrfs-progs-v6.16
 ./configure --disable-lzo --disable-documentation --disable-libudev --disable-zstd
 make -j$(nproc) btrfs
```

@zyxhere : would this be an acceptable approach for your usecase?

I suspect that setting `CFLAGS=$LDFLAGS` leads to CC effectively passing no arguments through to the linker. If this guess is correct, perhaps other linkers infer the need for LTO-like logic from the on-disk `*.o`, `*.a`, and `*.so` files, while `mold` requires us to be a bit more explicit?

<details>

<summary>Investigation prior to adjusting LDFLAGS (probably not relevant to others)</summary>

`reallocarray()` is a [C standard library function](https://www.man7.org/linux/man-pages/man3/reallocarray.3.html#:~:text=void%20%2Areallocarray%28void%20%2A%5FNullable%20p%2C%20size%5Ft%20n%2C%20size%5Ft%20size%29%3B), which glibc exports as a
[weak symbol](https://github.com/bminor/glibc/blob/master/malloc/reallocarray.c#L36).

```sh
$ readelf -sW /usr/lib/libc.so.6 | grep reallocarray | head -1
   135: 00000000000a9920    38 FUNC    WEAK   DEFAULT   14 reallocarray@@GLIBC_2.26
```

btrfs-progs contains a (re)definition of this function:

```sh
$ tail -n 7 libbtrfsutil/stubs.h
#ifndef _LIBBTRFSUTIL_STUBS_H_

#include <stddef.h>

void *reallocarray(void *ptr, size_t nmemb, size_t size);

#endif
```

```sh
$ tail -n 19 libbtrfsutil/stubs.c
#if HAVE_REALLOCARRAY != 1

#include <stdlib.h>
#include <errno.h>
#include "stubs.h"

void *reallocarray(void *ptr, size_t nmemb, size_t size)
{
        size_t res;

        res = nmemb * size;
        if (res < nmemb || res < size) {
                errno = ENOMEM;
                return NULL;
        }
        return realloc(ptr, res);
}

#endif
```

Without `-flto=auto` in CFLAGS, the build succeeds, and the static library
`libbtrfsutil.a` exposes a reasonable-looking strong global symbol:

```sh
$ readelf -sW libbtrfsutil.a | grep reallocarray
    48: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND reallocarray
     3: 0000000000000000    54 FUNC    GLOBAL HIDDEN     1 reallocarray
$ nm -C libbtrfsutil.a | grep -A100 '^stubs.o:'
stubs.o:
                 U __errno_location
                 U realloc
0000000000000000 T reallocarray
```

The `btrfs` utility (for example) reflects a successful link against the
`libbtrfsutil.a` static library's version of `reallocarray()`:

```sh
$ readelf -sW btrfs | grep reallocarray
  2196: 00000000000bfc90    54 FUNC    LOCAL  HIDDEN    27 reallocarray
$ ./btrfs --version | head -1
btrfs-progs v6.16
```

With `-flto`, `libbtrfsutil.a` looks different:

```sh
$ readelf -sW libbtrfsutil.a | grep -A100 stubs.o
File: libbtrfsutil.a(stubs.o)

Symbol table '.symtab' contains 3 entries:
   Num:    Value          Size Type    Bind   Vis      Ndx Name
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND
     1: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS stubs.c
     2: 0000000000000001     1 OBJECT  GLOBAL DEFAULT  COM __gnu_lto_slim
```

```sh
$ nm -C libbtrfsutil.a | grep -A100 '^stubs.o:'
nm: errors.o: plugin needed to handle lto object
nm: filesystem.o: plugin needed to handle lto object
nm: subvolume.o: plugin needed to handle lto object
nm: qgroup.o: plugin needed to handle lto object
nm: stubs.o: plugin needed to handle lto object
stubs.o:
0000000000000001 C __gnu_lto_slim
```

`lto-dump` seems to understand the object files:

```sh
$ lto-dump -list libbtrfsutil/stubs.o
Type   Visibility  Size  Name
function  hidden     0  __errno_location
function  hidden     0  realloc
function  hidden     6  reallocarray
```

... though I'm not sure yet about the resulting `libbtrfsutil.a` static library.

</details>

**Comment by etwoo** [comment]
I've been looking into this issue as a learning exercise and thought I'd post some experimental results, in case this information is helpful for others. Please excuse the noise if not!

I found the following changes each individually seemed to workaround this issue (not real fixes though):

1. delete the `reallocarray()` (re)definition from `libbtrfsutil/stubs.*` entirely, and allow `libbtrfsutil/subvolume.c` to use the C standard library version of `reallocarray()` instead
2. annotate the `reallocarray()` definition in `libbtrfsutil/stubs.h` with `__attribute__((visibility("default")))`
3. annotate the `reallocarray()` definition in `libbtrfsutil/stubs.h` with `__attribute__((used))`
4. use a modified build of mold with the following lines commented out from `src/passes.cc`: https://github.com/rui314/mold/blob/91439beea516f1ce51dc504bf475c4d596a84e9a/src/passes.cc#L314-L315

(4) makes me think this could be similar to the issue described in https://github.com/rui314/mold/commit/0612ea41f1a4dad4439e898b1d2a675bfd1e85a2

```
Assume both `foo.a` and `bar.so` define the same symbol `baz`.
If `baz`'s symbol visibility is hidden, it needs to be resolved within
the output file, i.e., from `foo.a`. However, previously, such symbol
was resolved to the one in `bar.so`.

To fix the problem, we'll lower the symbol priority for DSOs.
```

Something related might be happening here, with `libbtrfsutil.a` taking the place of `foo.a`, `libc.so` taking the place of `bar.so`, and `reallocarray()` taking the place of `baz`. My current best guess regarding control flow and in-memory state:

1. `libbtrfsutil/stubs.*` defines `reallocarray()`
2. `reallocarray()` ends up visible from `libbtrfsutil.a`
3. the only caller of this `reallocarray()` variant is actually `libbtrfsutil/subvolume.c`
4. `subvolume.c` gets compiled to `subvolume.o` and linked into the very same `libbtrfsutil.a` -- a seemingly prime candidate for LTO!
5. `get_symbols()` in `src/lto-unix.cc` sets `LDPR_PREVAILING_DEF_IRONLY` and `LDPR_RESOLVED_IR` for the definition of and  invocation of `reallocarray()` in `stubs.o`/`subvolume.o` within `libbtrfsutil.a`
6. based on the output of `src/lto-unix.cc`, LTO optimizes a lot of this away when linking the `btrfs` utility (for example) with `libbtrfsutil.a`, and `stubs.o` in `libbtrfsutil.a` becomes unreachable/unused
7. after `run_lto_plugin()` in `do_lto()`, the in-memory `Symbol` object corresponding to the `reallocarray()` symbol in `libc.so` still has `visibility == STV_HIDDEN`, like the variant of `reallocarray()` originally from `libbtrfsutil.a` -- maybe a kind of pollution, since `reallocarray()` from `libc.so` would not normally have this visibility value?
8. `do_lto()` calls `clear_symbols()` and `resolve_symbols()`
9. `visibility == STV_HIDDEN` causes `resolve_symbols()` in `src/passes.cc` to set `skip_dso = true` for this `Symbol` object: https://github.com/rui314/mold/blob/91439beea516f1ce51dc504bf475c4d596a84e9a/src/passes.cc#L314
10. `skip_dso = true` causes `SharedFile<E>::resolve_symbols()` in `src/input-files.cc` to skip processing this symbol, leaving `Symbol::file` unset: https://github.com/rui314/mold/blob/91439beea516f1ce51dc504bf475c4d596a84e9a/src/input-files.cc#L1413-L1414
11. `check_shlib_undefined()` in `src/passes.cc` errors out on the null value of `Symbol::file`: https://github.com/rui314/mold/blob/91439beea516f1ce51dc504bf475c4d596a84e9a/src/passes.cc#L1175-L1178

**Comment by schuettecarsten** [comment]
> Thank you for your report! This issue looks real and actually not limited to LTO. I'll try to address it later this week.

Hey, any news on this issue?
OpenWRT just merged a patch that excludes btrfs-progs from mold, but that's of course only a workaround...

**Comment by rui314** [comment]
No longer reproducible with git head.
