### ISSUE TITLE
Fails to build with Clang 15 and libstdc++12

### ISSUE THREAD

**Issue by mrjoel** [rui314/mold#1505]
When trying to build mold 2.40.4 with Clang 15 against libstdc++-12 (Debian bookworm), it fails to build with the error below, even if adding the `-fexperimental-library` option via `CMAKE_CXX_FLAGS`. It does successfully build with Clang 16 (and presumably later, confirmed Clang 20). Notably, the ranges and concepts support in Clang was slower developing.

The README still claims support for Clang 12.0.0 (or later), should that be updated, newer feature not used in code, or an additional compiler flag added when building with an older version?

The latest release which appears to build with this setup is 2.37.x, 2.38.0 and later fail to build in this configuration.

```
In file included from /mold-build/src/input-files.cc.X86_64.cc:3:
In file included from /mold-2.38.0/src/input-files.cc:1:
In file included from /mold-2.38.0/src/mold.h:3:
In file included from /mold-2.38.0/src/../lib/common.h:25:
In file included from /mold-2.38.0/third-party/tbb/src/tbb/../../include/tbb/concurrent_vector.h:17:
In file included from /mold-2.38.0/third-party/tbb/src/tbb/../../include/tbb/../oneapi/tbb/concurrent_vector.h:29:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/algorithm:63:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_algo.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_util.h:133:24: error: constraints not satisfied for alias template 'sentinel_t' [with _Range = std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>]
        && sized_sentinel_for<sentinel_t<_Derived>, iterator_t<_Derived>>
                              ^~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_util.h:228:29: note: in instantiation of template class 'std::ranges::view_interface<std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>>' requested here
    class subrange : public view_interface<subrange<_It, _Sent, _Kind>>
                            ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_algo.h:2220:7: note: in instantiation of template class 'std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>' requested here
      operator()(_Range&& __r, const _Tp& __value,
      ^
/mold-2.38.0/src/input-files.cc:1488:23: note: in instantiation of function template specialization 'std::ranges::__equal_range_fn::operator()<std::vector<mold::Symbol<mold::X86_64> *> &, mold::Integer<unsigned long, true, 8>, (lambda at /mold-2.38.0/src/input-files.cc:1489:43), std::ranges::less>' requested here
  auto [begin, end] = ranges::equal_range(sorted_syms, sym->esym().st_value, {},
                      ^
/mold-2.38.0/src/input-files.cc:1570:16: note: in instantiation of member function 'mold::SharedFile<mold::X86_64>::get_symbols_at' requested here
template class SharedFile<E>;
               ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_base.h:597:12: note: because 'std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>' does not satisfy 'range'
  template<range _Range>
           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_base.h:585:2: note: because 'ranges::begin(__t)' would be invalid: no matching function for call to object of type 'const __cust_access::_Begin'
        ranges::begin(__t);
        ^
In file included from /mold-build/src/input-files.cc.X86_64.cc:3:
In file included from /mold-2.38.0/src/input-files.cc:1:
In file included from /mold-2.38.0/src/mold.h:3:
In file included from /mold-2.38.0/src/../lib/common.h:25:
In file included from /mold-2.38.0/third-party/tbb/src/tbb/../../include/tbb/concurrent_vector.h:17:
In file included from /mold-2.38.0/third-party/tbb/src/tbb/../../include/tbb/../oneapi/tbb/concurrent_vector.h:29:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/algorithm:63:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_algo.h:36:
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_util.h:139:24: error: constraints not satisfied for alias template 'sentinel_t' [with _Range = const std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>]
        && sized_sentinel_for<sentinel_t<const _Derived>,
                              ^~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_base.h:597:12: note: because 'const std::ranges::subrange<__gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, __gnu_cxx::__normal_iterator<mold::Symbol<mold::X86_64> **, std::vector<mold::Symbol<mold::X86_64> *>>, std::ranges::subrange_kind::sized>' does not satisfy 'range'
  template<range _Range>
           ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/12/../../../../include/c++/12/bits/ranges_base.h:585:2: note: because 'ranges::begin(__t)' would be invalid: no matching function for call to object of type 'const __cust_access::_Begin'
        ranges::begin(__t);
        ^
...
```

**Comment by rui314** [comment]
Thanks for the report. It looks like clang-15 or earlier has issues with ranges.

https://stackoverflow.com/questions/77740451/why-does-calling-stdrangesrotate-on-a-vector-result-in-a-no-matching-functi

I'll update our README so that we recommend users use clang-16 or later to compile mold.

If you really wish to build mold with clang-15, I believe you can do that with libc++ by doing something like this

```
cmake -G Ninja \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_C_COMPILER=clang-15 \
  -DCMAKE_CXX_COMPILER=clang++-15 \
  -DCMAKE_CXX_FLAGS=-stdlib=libc++ \
  -DCMAKE_EXE_LINKER_FLAGS=-stdlib=libc++ \
  -DCMAKE_SHARED_LINKER_FLAGS=-stdlib=libc++
```

, but upgrading to clang-16 or later would be easier.
