### ISSUE TITLE
Spurious duplicate symbol with mixed LTO and non-LTO archives (regression from 920a5161)

### ISSUE THREAD

**Issue by jdrouhard** [rui314/mold#1637]
Since 2.42.0, a GCC LTO link against a non-LTO static archive can fail with a duplicate symbol error for a COMDAT symbol that both sides define — one that mold itself asked GCC to emit. GNU ld, gold and mold 2.41.0 all link the same inputs.

The invariant that breaks: once mold reports `LDPR_PREVAILING_DEF` for an IR definition, no regular object may also provide that symbol. Nothing carries that concession into the post-LTO round, where 920a5161 (the fix for #1565) now restarts COMDAT group selection from a clean slate. The reset is right when the pre-LTO winner was a regular object that is no longer extracted; it is too broad when the pre-LTO winner was an IR file, because the LTO output has no COMDAT group left to compete with.

Example with a shared ptr:

- **Pre-LTO round.** The only reachable files holding the COMDAT group for `_ZZNSt19_Sp_make_shared_tag5_S_tiEvE5__tag` are IR files, so an IR file claims the signature and mold reports `LDPR_PREVAILING_DEF` to the plugin. GCC therefore emits `__tag` into the LTRANS output as a plain `STB_GLOBAL` object **with no COMDAT group**.
- **Post-LTO round.** Members from a non-LTO archive become reachable. Nothing competes for the group (the LTRANS copy is not in one), the archive member wins it, its `STB_GNU_UNIQUE` copy stays live, and mold reports it as a duplicate of the definition it asked GCC to emit.

Mold 2.41.0 (bug not present) and mold 2.42.0 produce byte-identical plugin resolutions (`PREVAILING_DEF`) and byte-identical LTRANS output. Only the post-LTO COMDAT handling differs.

Confirmed by instrumenting `parse_input_sections()` to dump the reachable set per round. Pre-LTO every reachable holder of the group is an IR file; post-LTO 59 reachable *regular* objects hold it and the lowest-priority one takes ownership:

```
round 1 - reachable holders of the __tag group, all IR:
  IR 10004 <ir object>
  IR 11894 <ir archive member>
  ...
round 2 - reachable holders, all regular, lowest priority wins:
  REG 10077 <non-LTO archive member>   <-- wins the group, collides with the LTRANS copy
```

One further observation: on the same inputs GNU ld and gold answer `LDPR_PREVAILING_DEF_IRONLY`, so GCC emits `__tag` into the LTRANS output as a **local** symbol and no global collision is possible. mold answers `LDPR_PREVAILING_DEF` — "also referenced by a regular object" — which is what makes GCC emit a visible global. Both answers look defensible, but mold's is what creates the exposure.

## Reproduction 
```
mold 2.41.0                 PASS
mold 2.42.0                 FAIL
main (6e1d9b68)             FAIL
GNU ld 2.42 / gold 1.16     PASS
```
Needs real GCC — clang emits no `STB_GNU_UNIQUE` and drives LLVM LTO rather than GCC's linker plugin, so the link just succeeds and proves nothing. Tested with GCC 16.2.0.

<details>
<summary>shell script</summary>

```sh
#!/bin/bash
set -u
CXX="${CXX:-g++}"
AR="${AR:-ar}"
MOLD="${MOLD:-$(command -v mold)}"
LD="${LD:-mold}"      # mold | bfd | gold

DIR=$(mktemp -d); trap "rm -rf $DIR" EXIT

# Put both names in one -B dir so -fuse-ld reaches the binary we asked for rather
# than falling back to PATH: a mold build directory has ld but no ld.mold.
mkdir -p "$DIR/bin"
if [ "$LD" = mold ]; then
  ln -sf "$MOLD" "$DIR/bin/ld"
  ln -sf "$MOLD" "$DIR/bin/ld.mold"
fi
LDFLAGS="-B$DIR/bin -fuse-ld=$LD"

echo "compiler: $($CXX --version 2>/dev/null | head -1)"
echo "linker:   $($CXX $LDFLAGS -Wl,--version 2>/dev/null | head -1)"

# Non-LTO archive member, two roles:
#  1. std::make_shared gives it a COMDAT group for __tag whose definition GCC
#     emits with STB_GNU_UNIQUE binding.
#  2. It defines __divti3, which nothing references until LTRANS runs, so this
#     member is unreachable in the pre-LTO round and reachable in the post-LTO
#     one. Do not substitute __udivti3: libstdc++.so carries an undefined
#     reference to it, which extracts the member too early and hides the bug.
cat > "$DIR/util.cpp" <<'EOF'
#include <memory>
struct U { int x; };
int util_tag_user() { return std::make_shared<U>()->x; }
extern "C" __int128 __divti3(__int128 a, __int128 b) {
  return (__int128)((long long)a / ((long long)b | 1)) + util_tag_user();
}
EOF

# The IR side: make_shared puts the same COMDAT group in the IR file, and the
# 128-bit division makes LTRANS emit the call to __divti3.
cat > "$DIR/main.cpp" <<'EOF'
#include <memory>
struct A { int x; };
volatile unsigned long long lo = 7, hi = 3;
int main() {
  __int128 a = ((__int128)hi << 64) | lo;
  __int128 b = (__int128)lo + 1;
  return (int)(a / b) + std::make_shared<A>()->x;
}
EOF

CF="-std=c++20 -O2"
LF="$CF -flto=auto -fno-fat-lto-objects"
cd "$DIR"
$CXX $CF -c util.cpp -o util.o
$AR rcs libutil.a util.o
$CXX $LF -c main.cpp -o main.o

if $CXX $LF $LDFLAGS main.o libutil.a -o repro; then
  ./repro; echo "PASS (linked, binary exit $?)"
else
  echo "FAIL (spurious duplicate symbol)"
fi
```
</details>

Output with an affected mold:

```
mold: error: duplicate symbol: libutil.a(util.o): /tmp/ccXXXXXX.ltrans0.ltrans.o: std::_Sp_make_shared_tag::_S_ti()::__tag
collect2: error: ld returned 1 exit status
FAIL (spurious duplicate symbol)
```

**Comment by jdrouhard** [comment]
Thanks for the quick fix. @rui314 do you think it's possible to make a 2.42.1 point release that incorporates this? Thank you for considering!

**Comment by rui314** [comment]
The main trunk has a few new features, so I'll make a 2.43.0 release in a week or two.
