### ISSUE TITLE
Executable no longer links due to --no-allow-shlib-undefined: undefined symbol

### ISSUE THREAD

**Issue by WTassoux** [rui314/mold#1446]
Hello,

Upon upgrading the mold linker from version v2.35.1 to v2.38.1, we encountered an issue where we can no longer link our application using mold. The problem appears to be related to a shared library that imports a symbol from another library, which mold v2.38.1 flags as undefined.

This behavior is expected because the --no-allow-shlib-undefined option is now enabled by default. While this change aims to make mold consistent with other linkers, it seems to behave differently from our default linker, GNU ld. The same executable links successfully and runs with GNU ld 2.41. Below is the simplest reproducer I have managed to create:

f1.cpp
```
int f1()
{
  return 1;
}
```

f2.cpp
```
extern int f1();

int f2()
{
  return 42 + f1();
}

```

f3.cpp
```
extern int f1();

void f3()
{
  f1();
}
```

main.cpp
```
extern int f2();
extern int f3();

int main()
{
  return f2() + f3();
}
```

Compilation steps:
```
g++ -shared -fPIC f1.cpp -o libf1.so
g++ -shared -fPIC f2.cpp -L . -lf1 -o libf2.so
g++ -shared -fPIC f3.cpp -o libf3.so

g++ main.cpp -fPIC -L . -lf2 -lf3 -Wl,-rpath=. // Uses GNU ld, compiles and works (also compiles with -fuse-ld=gold)
mold -run g++ main.cpp -fPIC -L . -lf2 -lf3 -Wl,-rpath=. // Uses mold. Compiles and works in v2.35.1, not in v2.38.1 unless -Wl,--allow-shlib-undefined specified
```

**Comment by WTassoux** [comment]
I have tested the fix with version v2.39.0 and it works perfectly. Thanks for your work !
