### ISSUE TITLE
Test 6 - x86_64_ifunc-alias - fails with 9c355b7765a37069852a7cece99ddfdde10471d0

### ISSUE THREAD

**Issue by ms178** [rui314/mold#939]
I've just tried to compile 9c355b7765a37069852a7cece99ddfdde10471d0 with a very recent GCC 12.2.1 and LLVM/Clang-16 build, but Test 6 (x86_64_ifunc-alias) fails with both compilers and my usual flags.

Here is the console output:

```
++ dirname /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
+ . /tmp/makepkg/mold-git/src/mold/test/elf/common.inc
++ export LC_ALL=C
++ LC_ALL=C
++++ uname -m
+++ canonical_name x86_64
+++ case $1 in
+++ echo x86_64
++ HOST=x86_64
++ '[' -n '' ']'
++ MACHINE=x86_64
++ '[' -n '' ']'
++ CC=cc
++ CXX=c++
++ GCC=gcc
++ GXX=g++
++ OBJDUMP=objdump
++ OBJCOPY=objcopy
++ STRIP=strip
++ QEMU=
++ trap 'on_error $LINENO' ERR
++ trap on_exit EXIT
+++ basename /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh .sh
++ testname=x86_64_ifunc-alias
++ echo -n 'Testing x86_64_ifunc-alias ... '
Testing x86_64_ifunc-alias ... ++ t=out/test/elf/x86_64/x86_64_ifunc-alias
++ mkdir -p out/test/elf/x86_64/x86_64_ifunc-alias
+ cat
+ c++ -o out/test/elf/x86_64/x86_64_ifunc-alias/a.o -c -xc++ - -fno-PIE
+ c++ -B. -o out/test/elf/x86_64/x86_64_ifunc-alias/exe out/test/elf/x86_64/x86_64_ifunc-alias/a.o -static
mold: error: undefined symbol: _Z3foov()
>>> referenced by <stdin>
>>>               out/test/elf/x86_64/x86_64_ifunc-alias/a.o
collect2: error: ld returned 1 exit status
++ on_error 26
++ code=1
++ echo 'command failed: 26: $CXX -B. -o $t/exe $t/a.o -static'
command failed: 26: $CXX -B. -o $t/exe $t/a.o -static
++ trap - EXIT
++ exit 1

``

**Comment by rui314** [comment]
Can you edit the test file to remove `-B.` from the command line and run the test again, so that the test runs not with mold but with the default linker. Does it pass with that change?

**Comment by ms178** [comment]
That's what I got with GCC/ld with the modified test file:

```
❯ sh /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
Testing x86_64_ifunc-alias ... /usr/bin/ld: out/test/elf/x86_64/x86_64_ifunc-alias/a.o:(.data+0x0): undefined reference to `_Z3foov()'
collect2: error: ld returned 1 exit status
command failed: 26: $CXX -o $t/exe $t/a.o -static
```

**Comment by ms178** [comment]
I've just verified that ccd47db91653aebacc52dd3b6fb7833990122dc3 is the first bad commit where the test was introduced.

**Comment by ms178** [comment]
Could it be a factor that I build mold with TBB as static library?

```
  cmake \
  -S "$reponame" \
  -B build \
  -DCMAKE_BUILD_TYPE='Release' \
  -DCMAKE_INSTALL_PREFIX='/usr' \
  -DCMAKE_INSTALL_LIBEXECDIR='lib' \
  -DMOLD_USE_SYSTEM_MIMALLOC=OFF \
  -DMOLD_USE_SYSTEM_TBB=OFF \
  -DCMAKE_C_STANDARD=23 \
  -DCMAKE_CXX_STANDARD=20 \
  -DMOLD_USE_MOLD=ON \
  -DMOLD_LTO=ON

  cmake --build build
```

**Comment by ms178** [comment]
I still can reproduce the test failure on a clean install, if I install mold regardless of that error, I now see the following segfaults when compiling llvm-git and lib32-llvm-git (the latter build failed):

```
[  +0,861207] ld.mold[234345]: segfault at 572019c8 ip 0000557b57e5af0b sp 00007fc582bef768 error 4 cpu 9 in mold[557b57412000+a6e000] likely on CPU 9 (core 16, socket 0)
[  +0,000014] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
[  +0,050529] ld.mold[234175]: segfault at 742019c8 ip 0000559774e5af0b sp 00007f042bbf9768 error 4 cpu 0 in mold[559774412000+a6e000] likely on CPU 0 (core 0, socket 0)
[  +0,000022] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
[  +0,016191] ld.mold[234260]: segfault at e96019c8 ip 000055b7ea25af0b sp 00007fb07c9f3768 error 4 cpu 2 in mold[55b7e9812000+a6e000] likely on CPU 2 (core 2, socket 0)
[  +0,000015] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
[  +0,007119] ld.mold[233978]: segfault at 656019c8 ip 000055996625af0b sp 00007f34beffd768 error 4 cpu 10 in mold[559965812000+a6e000] likely on CPU 10 (core 17, socket 0)
[  +0,000013] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
[  +0,095696] ld.mold[233835]: segfault at 4cc019c8 ip 0000555b4d85af0b sp 00007fa531bfe658 error 4 cpu 20 in mold[555b4ce12000+a6e000] likely on CPU 20 (core 2, socket 0)
[  +0,000015] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
[  +0,102505] ld.mold[234653]: segfault at da2019c8 ip 00005574dae5af0b sp 00007fa7709ea768 error 4 cpu 25 in mold[5574da412000+a6e000] likely on CPU 25 (core 10, socket 0)
[  +0,000016] Code: b6 46 04 48 8d 0d 6d 68 3a ff 48 63 14 81 48 01 ca ff e2 8b 07 c3 0f b6 07 c3 0f b7 07 c3 00 0f b6 42 04 48 8d 0d fd 68 3a ff <48> 63 04 81 48 01 c8 ff e0 89 37 c3 40 88 37 c3 66 89 37 c3 00 80
```

**Comment by rui314** [comment]
```
+ c++ -o out/test/elf/x86_64/x86_64_ifunc-alias/a.o -c -xc++ - -fno-PIE
+ c++ -B. -o out/test/elf/x86_64/x86_64_ifunc-alias/exe out/test/elf/x86_64/x86_64_ifunc-alias/a.o -static
```

It's odd that `c++` is invoked here, as it should be `cc`. Did you accidentally specify c++ as a C compiler name?

**Comment by ms178** [comment]
No, I've just followed the instruction for exercising that test.

**Comment by rui314** [comment]
Can you copy-n-paste the command line?

**Comment by ms178** [comment]
The same as mentioned in https://github.com/rui314/mold/issues/939#issuecomment-1367988116 - I've only modified the test as you asked me to.

**Comment by rui314** [comment]
Please try again with `bash`.

```
bash /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
```

**Comment by ms178** [comment]
I get the same output while using `bash` on that modified test.

```
❯ bash /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
Testing x86_64_ifunc-alias ... /usr/bin/ld: out/test/elf/x86_64/x86_64_ifunc-alias/a.o:(.data+0x0): undefined reference to `_Z3foov()'
collect2: error: ld returned 1 exit status
command failed: 26: $CXX -o $t/exe $t/a.o -static
```

I've also now set

```
  -DMOLD_USE_MOLD=OFF \
  -DMOLD_LTO=OFF
```

and used Clang-16/LLD but still get:
```
++ dirname /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
+ . /tmp/makepkg/mold-git/src/mold/test/elf/common.inc
++ export LC_ALL=C
++ LC_ALL=C
++++ uname -m
+++ canonical_name x86_64
+++ case $1 in
+++ echo x86_64
++ HOST=x86_64
++ '[' -n '' ']'
++ MACHINE=x86_64
++ '[' -n '' ']'
++ CC=cc
++ CXX=c++
++ GCC=gcc
++ GXX=g++
++ OBJDUMP=objdump
++ OBJCOPY=objcopy
++ STRIP=strip
++ QEMU=
++ trap 'on_error $LINENO' ERR
++ trap on_exit EXIT
+++ basename /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh .sh
++ testname=x86_64_ifunc-alias
++ echo -n 'Testing x86_64_ifunc-alias ... '
Testing x86_64_ifunc-alias ... ++ t=out/test/elf/x86_64/x86_64_ifunc-alias
++ mkdir -p out/test/elf/x86_64/x86_64_ifunc-alias
+ cat
+ c++ -o out/test/elf/x86_64/x86_64_ifunc-alias/a.o -c -xc++ - -fno-PIE
+ c++ -B. -o out/test/elf/x86_64/x86_64_ifunc-alias/exe out/test/elf/x86_64/x86_64_ifunc-alias/a.o -static
mold: error: undefined symbol: _Z3foov()
>>> referenced by <stdin>
>>>               out/test/elf/x86_64/x86_64_ifunc-alias/a.o
collect2: error: ld returned 1 exit status
++ on_error 26
++ code=1
++ echo 'command failed: 26: $CXX -B. -o $t/exe $t/a.o -static'
command failed: 26: $CXX -B. -o $t/exe $t/a.o -static
++ trap - EXIT
++ exit 1
```

And after modifying the test, I still see:
```
❯ bash /tmp/makepkg/mold-git/src/mold/test/elf/x86_64_ifunc-alias.sh
Testing x86_64_ifunc-alias ... /usr/bin/ld: out/test/elf/x86_64/x86_64_ifunc-alias/a.o:(.data+0x0): undefined reference to `_Z3foov()'
collect2: error: ld returned 1 exit status
command failed: 26: $CXX -o $t/exe $t/a.o -static
```

**Comment by ms178** [comment]
Ah, success! I've tried the default distro toolchain and that works perfectly. Hence I suppose the test revealed a problem in my toolchain which also manifests in the following erros if I compile with Clang:

```
In file included from /tmp/makepkg/mold-git/src/mold/elf/mold-wrapper.c:11:
/usr/include/stdlib.h:141:8: error: unknown type name '_Float32'
extern _Float32 strtof32 (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:147:8: error: unknown type name '_Float64'
extern _Float64 strtof64 (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:153:8: error: unknown type name '_Float128'
extern _Float128 strtof128 (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:159:8: error: unknown type name '_Float32x'
extern _Float32x strtof32x (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:165:8: error: unknown type name '_Float64x'
extern _Float64x strtof64x (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:234:10: error: unknown type name '_Float32'
                       _Float32 __f)
                       ^
/usr/include/stdlib.h:240:10: error: unknown type name '_Float64'
                       _Float64 __f)
                       ^
/usr/include/stdlib.h:246:4: error: unknown type name '_Float128'
                        _Float128 __f)
                        ^
/usr/include/stdlib.h:252:4: error: unknown type name '_Float32x'
                        _Float32x __f)
                        ^
/usr/include/stdlib.h:258:4: error: unknown type name '_Float64x'
                        _Float64x __f)
                        ^
/usr/include/stdlib.h:317:8: error: unknown type name '_Float32'
extern _Float32 strtof32_l (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:324:8: error: unknown type name '_Float64'
extern _Float64 strtof64_l (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:331:8: error: unknown type name '_Float128'
extern _Float128 strtof128_l (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:338:8: error: unknown type name '_Float32x'
extern _Float32x strtof32x_l (const char *__restrict __nptr,
       ^
/usr/include/stdlib.h:345:8: error: unknown type name '_Float64x'
extern _Float64x strtof64x_l (const char *__restrict __nptr,

```

**Comment by rui314** [comment]
Cool! I don't know why it got `c++` instead of `cc` when it was run by `sh` instead of `bash`, but anyways, thank you for testing mold and reporting an issue!
